config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :index]

  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  root 'home#index'
  get 'home/about' => 'home#about'

  get 'users/:id/follows' => 'relationships#follows'
  get 'users/:id/followers' => 'relationships#followers'

  get '/search' => 'search#search'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  	@model = params["search"]["model"]
  	@content = params["search"]["content"]
  	@how = params["search"]["how"]
  	@dates = search_for(@how,@model,@content)
  end

  private

  def match(model,content)
  	if model =='user'
  		User.where(name: content)
  	elsif model == 'book'
  		Book.where(title: content)
  	end
  end

  def forward(model,content)
  	if model == 'user'
  		User.where("name LIKE?","#{content}%")
  	elsif model == 'book'
  		Book.where("title LIKE?","#{content}%")
  	end
  end

  def backward(model,content)
  	if model == 'user'
  		User.where("name LIKE?","%#{content}")
  	elsif model == 'book'
  		Book.where("title LIKE?","%#{content}")
  	end
  end

  def partical(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how,model,content)
  	case how
  	when 'match'
  		match(model,content)
  	when 'forward'
  		forward(model,content)
  	when 'backward'
  		backward(model,content)
  	when 'partical'
  		partical(model,content)
  	end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
    <div class="col-xs-9">
      <h2>Users search for'<%= @model %>'</h2>
      <table class="table table-hover teble-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th><%= @model %></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <% if @model == 'user' %>
          <% @dates.each do |date| %>
            <td><%= attachment_image_tag date, :profile_image, size:'50x50', format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= date.name %></td>
            <td></td>
            <td><%= link_to "Show", user_path(date) %></td>
            <% end %>
          <% else %>
          <% @dates.each do |date| %>
            <td><%= attachment_image_tag date.user, :profile_image, size:'50x50', format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= date.title %></td>
            <td></td>
            <td><%= link_to "Show", book_path(date) %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>