config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :index]

  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  root 'home#index'
  get 'home/about' => 'home#about'

  get 'users/:id/follows' => 'relationships#follows'
  get 'users/:id/followers' => 'relationships#followers'

  get '/search' => 'search#search'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, length: { in: 1..200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]
	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@books = Book.all
		@user = current_user
		@book.user_id = @user.id
        if @book.save
           flash[:notice] = "Book was successfully created."
  	       redirect_to book_path(@book)
        else
           render("books/index")
        end
	end

	def index
		@books = Book.page(params[:page]).reverse_order
		@book = Book.new
		@user = current_user
	end

	def show
		@book = Book.new
		@books = Book.find(params[:id])
		@user = @books.user
		@book_comment = BookComment.new
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	def edit
		@book = Book.find(params[:id])
		@user = current_user
	end

	def update
		@book = Book.find(params[:id])
		@book.update(book_params)

		if @book.save
			flash[:notice] = "You have update book successfully"
			redirect_to book_path(@book.id)
		else
			render("books/edit")
		end
	end

	private

    def correct_user
    	book = Book.find(params[:id])
    	if current_user != book.user
    		redirect_to books_path
    	end
    end

    def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<div class='container'>
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class='table'>
          <tbody>
            <tr></tr>
            <tr>
    	        <th>name</th>
    	        <th><%= user.name %></th>
            </tr>
            <tr>
    	        <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>
              <th>follows</th>
              <th><%= link_to user.followings.count, "/users/#{user.id}/follows" %></th>
            </tr>
            <tr>
              <th>followers</th>
              <th><%= link_to user.followers.count, "/users/#{user.id}/followers"  %></th>
            </tr>
          </tbody>
        </table>
        <%= render 'relationships/follow_button', user: user %>
        <span class= "row">
        <% if user.id == current_user.id %>
          <p><%= link_to "", edit_user_path(user),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user" %></p>
        <% end %>
        </span>

        <h2>New book</h2>
        <%= form_for(book, url: '/books') do |f| %>

        <h4>Title</h4>
        <%= f.text_field :title %>

        <h4>Body</h4>
        <%= f.text_area :body %>
        <br>
        <%= f.submit 'Create Book' %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
   <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
     <ul>
       <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
       <% end %>
     </ul>
<% end %>

<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

  <h5>Title</h5>
  <%= f.text_field :title %>

  <h5>Opinion</h5>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' %>

  <%= link_to "Show", book_path(@book) %>

  <%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
   <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
     <ul>
       <% @book.errors.full_messages.each do |message| %>
       <p><li><%= message %></li></p>
       <% end %>
     </ul>
<% end %>

<%= render 'books/list', book: @book, user: @user %>

    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover teble-inverse">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>opinion</th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <% @books.each do |book| %>
            <td>
              <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, size:'50x50', format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
              <div id="favorites_buttons_<%= book.id %>">
              <%= render partial: 'favorites/favorite', locals: { book: book} %>
              </div>
            </td>
            <td>コメント数 : <%= book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p><%= flash[:notice] %></p>

<%= render 'books/list', book: @book, user: @user %>

    <div class="col-xs-9">
      <h2>Book detail</h2>
      <table class="table table-hover teble-inverse">
       <tbody>
        <tr>
          <td><%= link_to user_path(@user) do %>
          <%= attachment_image_tag @user, :profile_image, size:'50x50', format: 'jpeg', fallback: "no_image.jpg" %>
          <% end %>
          <%= link_to @user.name, user_path(@user) %></td>

          <td><%= link_to @books.title, book_path %></td>
          <td><%= @books.body %></td>
          <td>
            <div id="favorites_buttons_<%= @books.id %>">
            <%= render partial: 'favorites/favorite', locals: { book: @books} %>
            </div>
          </td>
          <td>コメント数 : <%= @books.book_comments.count %></td>

          <% if @books.user_id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path %></td>
          <td><%= link_to "Destroy", book_path, method: :delete %></td>
          <% end %>
        </tr>
       </tbody>
      </table>

      <table id= "comments_area_<%= @books.id %>" class="table table-hover teble-inverse">
        <%= render partial: 'book_comments/comment_index', locals: { books: @books} %>
      </table>
      <% if @book_comment.errors.any? %>
        <h3><%= @book_comment.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book_comment.errors.full_messages.each do |message| %>
          <p><li><%= message %></li></p>
          <% end %>
        </ul>
      <% end %>
      <%= render partial: 'book_comments/comment_form', locals: { books: @books, book_comment: @book_comment} %>
    </div>
  </div>
</div>