config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :index]

  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  root 'home#index'
  get 'home/about' => 'home#about'

  get 'users/:id/follows' => 'relationships#follows'
  get 'users/:id/followers' => 'relationships#followers'

  get '/search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
  	favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, length: { in: 1..200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end

    def after_sign_in_path_for(resource)
    	user_path(resource)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]
	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@books = Book.all
		@user = current_user
		@book.user_id = @user.id
        if @book.save
           flash[:notice] = "Book was successfully created."
  	       redirect_to book_path(@book)
        else
           render("books/index")
        end
	end

	def index
		@books = Book.page(params[:page]).reverse_order
		@book = Book.new
		@user = current_user
	end

	def show
		@book = Book.new
		@books = Book.find(params[:id])
		@user = @books.user
		@book_comment = BookComment.new
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	def edit
		@book = Book.find(params[:id])
		@user = current_user
	end

	def update
		@book = Book.find(params[:id])
		@book.update(book_params)

		if @book.save
			flash[:notice] = "You have update book successfully"
			redirect_to book_path(@book.id)
		else
			render("books/edit")
		end
	end

	private

    def correct_user
    	book = Book.find(params[:id])
    	if current_user != book.user
    		redirect_to books_path
    	end
    end

    def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		@book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: @book.id)
        favorite.save

	end

	def destroy
		@book = Book.find(params[:book_id])
        favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
        favorite.destroy

	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  	@model = params["search"]["model"]
  	@content = params["search"]["content"]
  	@how = params["search"]["how"]
  	@dates = search_for(@how,@model,@content)
  end

  private

  def match(model,content)
  	if model =='user'
  		User.where(name: content)
  	elsif model == 'book'
  		Book.where(title: content)
  	end
  end

  def forward(model,content)
  	if model == 'user'
  		User.where("name LIKE?","#{content}%")
  	elsif model == 'book'
  		Book.where("title LIKE?","#{content}%")
  	end
  end

  def backward(model,content)
  	if model == 'user'
  		User.where("name LIKE?","%#{content}")
  	elsif model == 'book'
  		Book.where("title LIKE?","%#{content}")
  	end
  end

  def partical(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how,model,content)
  	case how
  	when 'match'
  		match(model,content)
  	when 'forward'
  		forward(model,content)
  	when 'backward'
  		backward(model,content)
  	when 'partical'
  		partical(model,content)
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])

  	if @user.update(user_params)
       flash[:notice] = "Book was successfully updated."
  	   redirect_to user_path(@user.id)
    else
       render("users/edit")
    end
  end

  def index
  	@users = User.all
  	@user = current_user
  	@book = Book.new
  end

  private

  def correct_user
      user = User.find(params[:id])
      if current_user != user
        redirect_to user_path(current_user)
      end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <h4>Bookers</h4>
        </nav>

      <% if user_signed_in? %>
        <nav>
          <ul class="nav navbar-nav navbar-right">

            <li class=""><%= link_to ' Home', user_path(current_user.id),class:"glyphicon glyphicon-home home" %></li>
            <li class=""><%= link_to ' Users', users_path,class:"glyphicon glyphicon-user users" %></li>
            <li class=""><%= link_to ' Books', books_path,class:"glyphicon glyphicon-book books" %></li>
            <li class=""><%= link_to " logout", destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out" %></li>
          </ul>
        </nav>
      <% else %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li class=""><%= link_to " Home", root_path,class:"glyphicon glyphicon-home home" %></li>
            <li class=""><%= link_to " About", home_about_path,class:"glyphicon glyphicon-link about" %></li>
            <li class=""><%= link_to " sign up", new_user_registration_path,class:"glyphicon glyphicon-edit sign_up" %></li>
            <li class=""><%= link_to " login", new_user_session_path,class:"glyphicon glyphicon-log-in sign-in" %></li>
          </ul>
        </nav>
      <% end %>
      </div>
    </header>
    <br>
    <br>
    <br>
      <% if user_signed_in? %>
        <div class="search-form">
          <%= form_tag(search_path, method: :get) do %>
          <%= text_field_tag 'search[content]' %>
          <%= select_tag 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
          <%= select_tag 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
          <%= submit_tag '検索', class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>

    <%= yield %>
  </body>
</html>